İş Başvurularının Yapay Zeka ile Değerlendirilmesi

Decision Tree kullanılır.

In [93]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [95]:
df = pd.read_csv('DecisionTreesClassificationDataSet.csv')
df.head()

Deneyim Yili SuanCalisiyor?  Eski Calistigi Firmalar Egitim Seviyesi  \
0            11              Y                        4              BS   
1             0              N                        0             PhD   
2             5              Y                        2              MS   
3             3              N                        1              BS   
4             0              N                        0              BS   

  Top10 Universite? StajBizdeYaptimi? IseAlindi  
0                 N                 N         Y  
1                 Y                 Y         Y  
2                 N                 Y         Y  
3                 N                 Y         Y  
4                 N                 N         N

Tüm değerlerin sayısal olması gerekiyor bu yüzden Y ve N değerlerini 0 veya 1 olarak düzenliyoruz.

In [98]:
duzetme_mapping = {'Y': 1, 'N': 0}

df['IseAlindi'] = df['IseAlindi'].map(duzetme_mapping)
df['SuanCalisiyor?'] = df['SuanCalisiyor?'].map(duzetme_mapping)
df['Top10 Universite?'] = df['Top10 Universite?'].map(duzetme_mapping)
df['StajBizdeYaptimi?'] = df['StajBizdeYaptimi?'].map(duzetme_mapping)

In [100]:
duzetme_mapping2 = {'BS': 0, 'MS': 1, 'PhD': 2}

df['Egitim Seviyesi'] = df['Egitim Seviyesi'].map(duzetme_mapping2)

In [102]:
df.head()

Deneyim Yili  SuanCalisiyor?  Eski Calistigi Firmalar  Egitim Seviyesi  \
0            11               1                        4                0   
1             0               0                        0                2   
2             5               1                        2                1   
3             3               0                        1                0   
4             0               0                        0                0   

   Top10 Universite?  StajBizdeYaptimi?  IseAlindi  
0                  0                  0          1  
1                  1                  1          1  
2                  0                  1          1  
3                  0                  1          1  
4                  0                  0          0

Bağımlı ve Bağımsız değişkenlerimizi seçiyoruz.

In [105]:
y = df['IseAlindi']
x = df.drop(['IseAlindi'], axis=1)

Decision Tree'yi oluşturuyoruz.

In [108]:
clf = DecisionTreeClassifier().fit(x,y)

[1] gelirse işe alınır. [0} gelirse işe alınmaz.

In [110]:
clf.predict([[5,1,3,0,0,0]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [113]:
clf.predict([[2,0,7,0,1,0]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [115]:
clf.predict([[2,1,7,0,0,0]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [117]:
clf.predict([[20,0,5,1,1,1]])

C:\Users\dlara\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)